name: LPHK
channels:
  - defaults
dependencies:
  - python=3.7*
  - pip
  - tk
  - pip:
    - git+git://github.com/FMMT666/launchpad.py.git@master
    - pillow
    - pygame
    - pynput
    - tkcolorpicker
    - py-getch
    - pyautogui
    - pywin32
    - pytesseract
    - imagehash
    - dhash
    - selenium
    - pyperclip
    - python-dateutils
